### ISSUE TITLE
Can't access Static files

### ISSUE THREAD

**Issue by Errechydy** [ZakMiller/NestWithVue#35]
When running 

`npm run start:dev`

And accessing `http://localhost:3000` i get this error 
```
 [ExceptionsHandler] ENOENT: no such file or directory, stat 'NestWithVue/client/dist/index.html' +5965ms
Error: ENOENT: no such file or directory, stat 'NestWithVue/client/dist/index.html'
```

**Comment by hnviradiya** [comment]
Your build is successful?

**Comment by Errechydy** [comment]
Yes, my bad, i should add  `../`.in the `rootPath` like this

 `rootPath: join(__dirname, '..', '../static/dist'),` 

I guess because i set  `setGlobalPrefix` in the `main.ts` to `api/v1`  instead of just `api`
